language: php
php:
  - 5.5
  - 5.6

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - cp app/phpunit.xml.dist app/phpunit.xml
  - composer install

script: 'vendor/phpunit/phpunit/phpunit -c app/phpunit.xml'
